spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: '2.0'

cards:
  message: "Welcome to EazyBank cards related QA APIs"
  contactDetails:
    name: " Jane Doe - QA Lead"
    email: "jane@eazybank.com"
  onCallSupport:
    - (+91)0987654321