services:
  accounts:
    image: "sh5800/accounts:s4"
#    container: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
         memory: 700m
    networks:
      - eazybank
  loans:
      image: "sh5800/loans:s4"
#      container: loans-ms
      ports:
        - "8090:8090"
      deploy:
        resources:
          limits:
           memory: 700m
      networks:
            - eazybank
  cards:
      image: "sh5800/cards:s4"
#      container: cards-ms
      ports:
        - "9000:9000"
      deploy:
        resources:
          limits:
           memory: 700m
      networks:
            - eazybank
networks:
  eazybank:
    driver: "bridge"